export const EXPAND_MENU = 'EXPAND_MENU'

export const SELECT_MENU = 'SELECT_MENU'

export const SELECT_CANVAS = 'SELECT_CANVAS'

export const SET_SHOW_TAGS = 'SET_SHOW_TAGS'

export const SHOW_TAGS_MENU_TOGGLE = 'SHOW_TAGS_MENU_TOGGLE'

export const SEGMENTATION_VISIBLE_TOGGLE = 'SEGMENTATION_VISIBLE_TOGGLE'

export const SEGMENTATION_SELECTED_TOGGLE = 'SEGMENTATION_SELECTED_TOGGLE'
