export const MENU_CLICKED = 'MENU_CLICKED'

export const FILE_UPLOADED = 'FILE_UPLOADED'

export const FILE_UPLOADED_SEG = 'FILE_UPLOADED_SEG'

export const SHOW_SEGMENTATION_POPUP = 'SHOW_SEGMENTATION_POPUP'

export const SHOW_ANALYSIS_REPORT_POPUP = 'SHOW_ANALYSIS_REPORT_POPUP'
